from random import randint

# To generate a 4 digit number with unique digits.
# /return type:str the 4 digit generated number.
def makeUniqueNumber():
    # A list representing all the digits from 0 to 9.
    digits = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ]

    # The generated number.
    num = ""

    # Loop for times to generate a 4 digit number.
    for x in range(4):
        index = randint(0, len(digits) - 1)   # Get a random index from 0 to the length of digit minus 1.
        num += digits[index]                  # We add the digit to the number.
        digits.pop(index)                     # We remove the digit from the list so that the generated number has unique digits.
    
    # Return that number.
    return num

# Check whether the player's guess is close to the generated number.
# /param  num:str     the number generated by the program.
# /param  guess:str   the player's guess.
# /return type:tuple  the bulls and cows (index: bulls = 0, cows = 1)
def checkGuess(guess, num):
    # The number of bulls.
    bulls = 0

    # The number of cows.
    cows  = 0

    # Loop through each digit.
    for i in range(4):
        # Check if the number is a bull.
        if num[i] == guess[i]:
            # Increment bulls by 1.
            bulls += 1
        
        # Check if the number is a cow.
        elif guess[i] in num:
            # Increment cows by 1.
            cows  += 1
    
    # Return a tuple with bulls and cows as its elements
    return ( bulls, cows )

# Normalizes the user input so that it is atleast 4 digits.
# /param  num:str   the user input.
# /param  n:int     the number of digits.
# /return type:str  the normalized user input.
def normalizeInput(num, n):
    # The prefix for the num.
    prefix = ""

    # Loop for all the missing digits.
    for i in range(0, n - len(num)):
        prefix += '0'

    # Return the normalized user input.
    return prefix + num

# The entry point of the program.
# /return type:void
def main():
    # Generate a unique random number.
    answer = makeUniqueNumber()

    # Run the program forever until the user correctly guesses the number.
    while True:
        # Get the user's guess.
        guess = input("Enter a number: ")

        # Normalize the user input.
        guess = normalizeInput(guess, 4)

        # Get the bulls and cows.
        bullsAndCows = checkGuess(guess, answer)

        # If the guess is correct, exit out of the loop.
        if bullsAndCows[0] == 4:
            break
        
        # If the guess is not correct, notify the bulls and cows to the user.
        else:
            print(f"Bulls : {bullsAndCows[0]}")
            print(f"Cows  : {bullsAndCows[1]}\n")
    
    # Once the user guessed correctly, congratulate them!
    print("You have guessed the number correctly.")
    print("Congratulations, you have won the game~!")

if __name__ == "__main__":
    main()
